In [1]:
# 1. Write a function to normalize a list of numbers between 0 and 1
nums = [3, 6, 8, 11, 32, 6, 83]

def normalise(nums: list):
    # Handle empty lists to avoid errors
    if not nums:
        return []
        
    # Find the range (min and max)
    min_val = min(nums)
    max_val = max(nums)
    
    # Avoid division by zero if all numbers in the list are the same
    if max_val == min_val:
        return [0.0] * len(nums)
    
    # Calculate normalized values
    # Python performs float division by default with the / operator
    normalized = [(x - min_val) / (max_val - min_val) for x in nums]
    
    return normalized

print(normalise(nums))


[0.0, 0.0375, 0.0625, 0.1, 0.3625, 0.0375, 1.0]


In [2]:
# 2. Implement manual matrix multiplication (no NumPy)
def matrix_multiply(A, B):
    # Get dimensions
    rows_A = len(A)
    cols_A = len(A[0])
    rows_B = len(B)
    cols_B = len(B[0])

    # 1. Validation: Check if multiplication is possible
    if cols_A != rows_B:
        raise ValueError("Matrix dimensions incompatible for multiplication.")

    # 2. Initialize the result matrix with zeros
    # Result will be (rows_A x cols_B)
    result = [[0 for _ in range(cols_B)] for _ in range(rows_A)]

    # 3. Perform the multiplication
    for i in range(rows_A):          # Iterate through rows of A
        for j in range(cols_B):      # Iterate through columns of B
            for k in range(cols_A):  # Iterate through columns of A / rows of B
                result[i][j] += A[i][k] * B[k][j]

    return result

# Example Usage:
matrix_a = [
    [1, 2],
    [3, 4]
]

matrix_b = [
    [5, 6],
    [7, 8]
]

print(matrix_multiply(matrix_a, matrix_b))
# Output: [[19, 22], [43, 50]]

[[19, 22], [43, 50]]


In [6]:
# 3. Using NumPy, create a random 3D array (image-like) and print shape
import numpy as np

# Create a random 3D array 
# parameters: (height, width, channels)
# np.random.rand generates values between 0 and 1
image_array = np.random.rand(128, 128, 3)

# Print the shape and metadata
print(f"Shape of the array: {image_array.shape}")
print(f"Dimensions: {image_array.ndim}")
print(f"Total number of elements: {image_array.size}")

Shape of the array: (128, 128, 3)
Dimensions: 3
Total number of elements: 49152


In [7]:
# 4. Convert a list into a NumPy array and reshape it to (3, 3)
import numpy as np

# 1. Define a list with 9 elements
data_list = [10, 20, 30, 40, 50, 60, 70, 80, 90]

# 2. Convert to NumPy array
arr = np.array(data_list)

# 3. Reshape to 3x3
# Note: You can also do this in one line: np.array(data_list).reshape(3, 3)
matrix = arr.reshape(3, 3)

print("Original List:", data_list)
print("Reshaped Matrix:\n", matrix)
print("New Shape:", matrix.shape)

Original List: [10, 20, 30, 40, 50, 60, 70, 80, 90]
Reshaped Matrix:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
New Shape: (3, 3)


In [10]:
# 5. Compute mean, std, min, max of a NumPy array
import numpy as np
arr = [9,1,2,43,23,6]
data = np.array(arr)
mean = np.mean(data)
std = np.std(data)
min = np.min(data)
max = np.max(data)

print(mean)
print(std)
print(min)
print(max)

14.0
14.854853303438128
1
43


In [1]:
# 6. Normalize a NumPy array (image normalization)
import numpy as np
image = np.random.randint(0,256, (16,16,3), dtype = np.uint8)
# print(image)
img_min = np.min(image)
img_max = np.max(image)
norm_img = (image - img_min) / (img_max - img_min)
print(norm_img)

[[[0.63921569 0.11764706 0.13333333]
  [0.10196078 0.59215686 0.22745098]
  [0.38431373 0.08235294 0.86666667]
  [0.11764706 0.99607843 0.4745098 ]
  [0.82352941 0.23921569 0.22352941]
  [0.61176471 0.14509804 0.05882353]
  [0.58039216 0.28235294 0.63921569]
  [0.91764706 0.17254902 0.60784314]
  [0.39607843 0.69803922 0.54901961]
  [0.85882353 0.96078431 0.37647059]
  [0.58431373 0.61176471 0.96078431]
  [0.39607843 0.03137255 0.40784314]
  [0.63137255 0.32156863 0.14901961]
  [0.65490196 0.92941176 0.8       ]
  [0.3254902  0.10588235 0.18039216]
  [0.14901961 0.05882353 0.61568627]]

 [[0.90980392 0.35294118 0.80784314]
  [0.70980392 0.44313725 0.01176471]
  [0.50196078 0.65098039 0.43529412]
  [0.38431373 0.61960784 0.31372549]
  [0.63921569 0.17647059 0.82745098]
  [0.40392157 0.19215686 0.75686275]
  [0.96862745 0.94117647 0.94901961]
  [0.54117647 0.69019608 0.15294118]
  [0.87843137 0.27843137 0.18823529]
  [0.86666667 0.62352941 0.64313725]
  [0.43529412 0.56078431 0.89803922]

In [2]:
# 7. Slice a 3D array to extract one channel
print(image)
red = image[:,:,0]

[[[163  30  34]
  [ 26 151  58]
  [ 98  21 221]
  [ 30 254 121]
  [210  61  57]
  [156  37  15]
  [148  72 163]
  [234  44 155]
  [101 178 140]
  [219 245  96]
  [149 156 245]
  [101   8 104]
  [161  82  38]
  [167 237 204]
  [ 83  27  46]
  [ 38  15 157]]

 [[232  90 206]
  [181 113   3]
  [128 166 111]
  [ 98 158  80]
  [163  45 211]
  [103  49 193]
  [247 240 242]
  [138 176  39]
  [224  71  48]
  [221 159 164]
  [111 143 229]
  [245 185 150]
  [231 249 114]
  [134 249   4]
  [  7 166 225]
  [ 86  31  21]]

 [[168 227  76]
  [241  24 232]
  [161  15   0]
  [214 207 219]
  [  7 230 244]
  [ 24 219  49]
  [119 180  89]
  [ 35  84  39]
  [125  53  23]
  [ 64 210 163]
  [222 193  64]
  [226  28  69]
  [ 17 134 223]
  [189  22 114]
  [140  81 137]
  [173  26 162]]

 [[201 129   0]
  [ 91 229 148]
  [158 130  89]
  [235 240  65]
  [117  38  69]
  [ 54  92 218]
  [ 24 209 247]
  [209  92 147]
  [107 223 250]
  [206  91 141]
  [174 236   3]
  [ 85 227  63]
  [203 212 101]
  [  6 219  92]
  

In [8]:
# 8. Stack two arrays along a new axis
arr1 = np.ones((100,100))
arr2 = np.zeros((100,100))
arr3 = np.stack([arr1, arr2])
print(arr3.shape)

(2, 100, 100)


In [11]:
# 9. Write a function to convert grayscale to 3-channel image

def grayscale_to_rgb(grayscale):
    rgb = np.stack([grayscale, grayscale, grayscale], axis = -1)
    return rgb
grayscale = np.random.randint(0,256,(100,100), dtype = np.uint8)
rgb = grayscale_to_rgb(grayscale)
print(rgb.shape)

(100, 100, 3)


In [12]:

# 10. Clip values of an array between 0–

data = np.array([20, -10, 45, 345, 2,-1, 9387387, 234})
clipped_data = np.clip(data, 0, 255)

print(f"original data: {